version: "3"

services:
  nginx:
    image: project:nginx_ver1
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile

  httpd:
    image: project:httpd_ver1
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile

  php:
    image: project:php_ver1
    build: 
      context: ./
      dockerfile: ./docker/php/Dockerfile