version: "3"

services:
  mongo:
    image: mongo:3.6.3
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:4.0.9
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes: 
  mongo_data:
  redis_data: