version: "3"

services:
  apache:
    image: httpd
    ports: 
      - 80:80
    volumes: 
      - /var/run/php/php7.4-fpm.sock:/var/run/php/php7.4-fpm.sock
      - ./:/home/user/www/project
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
 
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_db

  mongo:
    image: mongo:3.6.3
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:4.0.9
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:10.12
    ports:
      - 5432:5432
    volumes: 
      - postgres_data:/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db


volumes: 
  mongo_data:
  redis_data:
  postgres_data:
  mysql_data: