version: "3"

services:
  nginx:
    image: nginx
    ports: 
      - 80:80
    volumes: 
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  httpd:
    image: httpd
    ports: 
      - 88:80
    volumes: 
      - ./:/var/www/app
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
 
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/app
    user: 1000:1000
    working_dir: /var/www/app/web

  mysql:
    image: mysql:5.7.29
    volumes:
      - mysql_data:/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_db

  mongo:
    image: mongo:3.6.3
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:4.0.9
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:10.12
    volumes: 
      - postgres_data:/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db


volumes: 
  mongo_data:
  redis_data:
  postgres_data:
  mysql_data: