<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%test}}`.
 */
class m200425_185927_create_pg_test_table extends Migration
{
    public function init()
    {
        $this->db = 'postgres';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%test}}', [
            'id' => $this->primaryKey(),
            'value' => $this->string(),
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%test}}');
    }
}
